### create the patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Alok",
  "email": "",
  "address": "123 abc cdwe",
  "dateOfBirth": "2002-06-24",
  "registeredDate": "2006-06-24"
}

###